### ISSUE TITLE
[Feature Request] Make consume-mode optional

### ISSUE THREAD

**Issue by Switch123456789** [dyj216/mopidy-yap#1]
Hey, nice interface, I hope you're still maintaining it :)
I ran into some weird issues recently with http-streams. The most obvious issue is that yap thinks nothing is playing when a http-stream is playing. I usually use a playlist with a single line that refers to the http-stream to start the stream. This works fine but as soon as I open the yap-interface at least once (after restarting mopidy), mopidy refuses to play this stream from the playlist (no error), if I add a single line (with a local file) in the playlist BEFORE the livestream, it plays the file and the stream perfectly fine.

**Comment by dyj216** [comment]
I will look into this. Can you provide an example http-stream?

**Comment by Switch123456789** [comment]
Thank you :) I did some more testing and narrowed down the issue a bit more.

If I activate mentioned playlist from Iris it is playing fine but if I activate the playlist through [this HomeAssistant integration](https://github.com/bushvin/hass-integrations) it will load the playlist but not play it (even if I press play manually, nothing happens) and at the same time the yap-ui becomes white & blank. With yap disabled, there are not such issues.

Here is a [playlist](https://github.com/dyj216/mopidy-yap/files/12968926/test.zip) with a random livestream I found on [xiph.org](http://dir.xiph.org/), if my linked stream is offline you could copy&paste a working stream-url from this website into the playlist.

**Comment by Switch123456789** [comment]
Two more things, if I activate a playlist by selecting a "Source" there are no issues, but if I start the stream by requesting the URI directly (of the playlist or the stream itself) the issue appears. I was also able to catch an error in the log.
```
ERROR    2023-10-18 02:05:07,099 [227:YapFrontend-14 (_actor_loop)] mopidy.listener
  Triggering event failed: track_playback_ended(tl_track, time_position)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mopidy/listener.py", line 44, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python3.11/site-packages/mopidy_yap/frontend.py", line 30, in track_playback_ended
    if self.config["spotify"] and self.config["spotify"]["enabled"] and self.config["yap"]["autoplay"]:
       ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mopidy/config/__init__.py", line 316, in __getitem__
    item = self._data.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'spotify'
```
I don't know what that means but I see spotify is mentioned several times, so maybe it is important to know that I don't have any spotify extensions installed.

**Comment by dyj216** [comment]
That error is programming error, I wanted to check if there is any specific spotify setting is in the config, but did not used the correct way to do so. I fixed that and released 0.1.4 with the fix, but I am not sure if this fixes your original problem. If not, then I will investigate further.

**Comment by Switch123456789** [comment]
Thank you :) the error message is gone now. However the main issue remained but I didn't see the site crash again yet. I just noticed that yap enables consume-mode and that caused the issues, I worked around that by running a Home Assistant script that disables it. I don't use yap if I play streams so that works for me. It still might be something to consider, maybe making it optional?

**Comment by Switch123456789** [comment]
I updated the title, because the issue was caused by mopidy's consume-mode, not yap directly. But it could still be useful to have a way to work with yap without the need of having consume-mode enabled.

**Comment by dyj216** [comment]
Thanks for the feedback. Originally, I force-enabled the consume-mode to circumvent the problem to only display the current and next tracks (as it is not that interesting what was before, and it would take a lot of effort to create a usable interface). I have released 0.1.5, which I hope would fix your problems, I also worked a little bit with the streams. You can not add a stream on this frontend, but yap should display it, and it is possible to skip to the next queue item.

Please give some feedback, if your issue is solved or not!

**Comment by Switch123456789** [comment]
Hey, happy new year & thank you very much! this will help streamline my setup here :)
Everything works fine now. Only exception is the way the queue-view behaves when shuffle is enabled. It makes not a lot of sense in this case. A simple solution (I hope) that comes to mind is to make it show the whole playlist only if shuffle is on.
